// Do not edit by hand. This file was generated by json-schema-aot.

export type HexColor = string;

/** Format for md2blog site metadata file (site.json). */
export interface SiteMetadata {
    /** Title for the site (displayed at the top of every page). */
    title: string;
    /** Optional (but recommended) description of the site (used in meta tags and also used as the default subtitle on all pages). */
    description?: string;
    /** Optional (but recommended) URL for the root of the site (used in Atom feed and Open Graph links). */
    url?: string;
    /** Optional object specifying colors to use on the site. Note that all colors are reused for syntax highlighting. */
    colors?: {
        /** Color used for the site title. */
        title?: HexColor;
        /** Color used for headings. */
        heading?: HexColor;
        /** Color used links. */
        link?: HexColor;
        /** Color used only for syntax highlighting (generally for comments). */
        comment?: HexColor;
    };
}

